#=======================================================
# Description: Build OpenWrt using GitHub Actions
# https://github.com/Hyy2001X/AutoBuild-Actions
# Lisence: MIT
# Author: P3TERX
# Modify: Hyy2001X
#=======================================================

name: AutoBuild-Sample

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH 连接到 Actions'
        required: true
        default: 'false'
      target_name:
        description: '设备名称 [必选]'
        default: 'x86_64'
      openwrt_sc:
        description: 'Openwrt 源码:分支 [必选]'
        default: 'coolsnowwolf/lede:master'
      ip_addr:
        description: '固件 IP 地址 [可选]'
        default: ''

env:
  DIY_SCRIPT: Scripts/AutoBuild_DiyScript.sh
  FUNCTION_SCRIPT: Scripts/AutoBuild_Function.sh
  UPLOAD_RELEASE: true
  UPLOAD_FIRMWARE: false
  UPLOAD_BIN_DIR: false
  REMOVE_USELESS_FILES: true
  REMOVE_WORKFLOW_RUNS: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization Defined Info
      run: |
        [[ -n "${{ github.event.inputs.target_name }}" ]] && {
            echo "设备名称: ${{ github.event.inputs.target_name }}"
        } || {
            echo "[ERROR] 未输入设备名称!"
            exit 1
        }
        [ ! -f "$GITHUB_WORKSPACE/Configs/${{ github.event.inputs.target_name }}" ] && {
            echo "[ERROR] 未检测到设备对应的 [${{ github.event.inputs.target_name }}] 的配置文件!"
            exit 1
        }
        URL_BRANCH=${{ github.event.inputs.openwrt_sc }}
        URL="https://github.com/$(echo $URL_BRANCH | egrep -o ".*:")"
        REPO_URL=${URL%?}
        REPO_BRANCH=$(echo $URL_BRANCH | egrep -o ":.*" | cut -c2-100)
        [[ -z $REPO_BRANCH ]] && REPO_BRANCH=master
        echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV
        echo "REPO_BRANCH=$REPO_BRANCH" >> $GITHUB_ENV
        echo -e "源码地址: $REPO_URL\n分支: $REPO_BRANCH"

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync qemu-utils
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        echo "Compile_Date=$(date +%Y%m%d%H%M)" > $GITHUB_WORKSPACE/Openwrt.info
        echo "Display_Date=$(date +%Y/%m/%d)" >> $GITHUB_WORKSPACE/Openwrt.info
        echo "Defined_IP_Address=${{ github.event.inputs.ip_addr }}" >> $GITHUB_WORKSPACE/Openwrt.info
        echo "Artifacts_Date=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        touch update_log.txt

    - name: Remove useless files
      if: env.REMOVE_USELESS_FILES == 'true' && !cancelled()
      run: |
        echo "Deleting useless files, please wait ..."
        docker rmi $(docker images -q)
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone Openwrt source code
      run: |
        git clone -b $REPO_BRANCH $REPO_URL openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        [ -f Configs/${{ github.event.inputs.target_name }} ] && cp Configs/${{ github.event.inputs.target_name }} openwrt/.config || {
            echo "未检测到该设备的 ${{ github.event.inputs.target_name }} 配置文件!"
            exit 1
        }
        cd openwrt
        ./scripts/feeds update -a > /dev/null 2>&1
        ./scripts/feeds install -a

    - name: Run Customize Diy-Scripts
      run: |
        chmod +x $DIY_SCRIPT
        chmod +x $FUNCTION_SCRIPT
        cd openwrt
        source $GITHUB_WORKSPACE/$DIY_SCRIPT
        source $GITHUB_WORKSPACE/$FUNCTION_SCRIPT
        Firmware-Diy_Base
        Firmware-Diy

    - name: Process Openwrt source code
      run: |
        cd openwrt
        ./scripts/feeds install -a
        make defconfig

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: Compile the Openwrt
      run: |
        cd openwrt
        make download -j8
        echo "Start to compile OpenWrt for $CONFIG_FILE..."
        make -j$(nproc) || make -j1 V=s

    - name: Process the AutoBuild Firmware
      run: |
        cd openwrt
        source $GITHUB_WORKSPACE/$FUNCTION_SCRIPT && PS_Firmware

    - name: Upload Firmware to Artifacts
      uses: actions/upload-artifact@main
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      with:
        name: ${{ github.event.inputs.target_name }}_${{ env.REPO_BRANCH }}_Firmware
        path: openwrt/bin/Firmware

    - name: Upload bin directory to Artifacts
      uses: actions/upload-artifact@main
      if: env.UPLOAD_BIN_DIR == 'true' && !cancelled()
      with:
        name: ${{ github.event.inputs.target_name }}_${{ env.REPO_BRANCH }}_BINDir
        path: openwrt/bin

    - name: Upload Firmware to Release
      uses: softprops/action-gh-release@v1
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: AutoUpdate
        body_path: update_log.txt
        files: openwrt/bin/Firmware/*

    - name: Remove workflow runs
      uses: GitRML/delete-workflow-runs@main
      if: env.REMOVE_WORKFLOW_RUNS == 'true' && !cancelled()
      with:
        retain_days: 1
        keep_minimum_runs: 3
